spymaster:
  model_name:   "gpt-3.5-turbo"
  prompt:       "You are playing the game Codenames. You are provided the following board state and team. Your target words are the words that belong to your team. Provide a one-word clue that relates to as many of your target words as possible, and provide the number of words. Response format: <Clue> <Number>. \nBoard: {board_state}\nTeam: {team}"
  # prompt:       "Given the following board state and team, provide a clue word and number.\nBoard: {board_state}\nTeam: {'Red' if team == 0 else 'Blue'}\nClue:" ## need to refine prompt

operative:
  model_name:   "gpt-3.5-turbo"
  prompt:       "You are playing the game Codenames. You are provided the following board state and team. The clue is {clue}, where the clue relates to {number} words on the board that are unrevealed. Guess a word that you think belongs to your team. Response format: <Word>. \nBoard: {board_state}"
  # prompt:       "Given the following board state and clue, guess a word.\nBoard: {board_state}\nClue: {clue}\nGuess:" ## need to refine prompt